### ISSUE TITLE
Implement push/getReceipts

### ISSUE THREAD

**Issue by babrama** [expo-community/expo-server-sdk-python#25]
Hello,

First of all, thanks a lot for you implementation, which I look forward to use in the coming days.

Quick question: Do you plan to implement also the push/getReceipts API ?

From what I can read, it is important to use it in order to check if a user has disabled notifications for this app.

Many thanks,
Bruno

**Comment by julianpacker** [comment]
This is implemented in #31 . Will be merged soon
