### ISSUE TITLE
Sending same message with multiple receiptens

### ISSUE THREAD

**Issue by emilpriver** [expo-community/expo-server-sdk-python#33]
Hello, Was looking at this repo to find out how to send the same message to maybe 1000 tokens at the same time without using creating a loop and building up a lot of messages, and using publish_multiple.

Is it possible to give an array of tokens to "to" in the "PushMessage" object?

**Comment by julianpacker** [comment]
I'm currently using a for loop that builds the same PushMessage (with a different token) and then calls publish_multiple.

I suppose it would be slightly more convenient if there were a class PushMessages which could take care of this. Or a convenient function that does this work for you. Is that the thing you're implying or did you have another idea?

**Comment by emilpriver** [comment]
Solved it with chunking the big array to chunks of 99 items per array. then looping thrue them and using publish_multiple to send them :D
