### ISSUE TITLE
Rename receipts to push-tickets ?

### ISSUE THREAD

**Issue by SibiAkkash** [expo-community/expo-server-sdk-python#38]
The [docs](https://docs.expo.io/push-notifications/sending-notifications/#push-tickets) have specified "push-tickets" to be the response that is returned when we push notifications to the Expo servers. And that "push-receipts" are receipts generated once Expo enqueues the notifications to FCM and APNs. These receipts are queried with the IDs present in the push-tickets. 
In `publish_internal()` the push_tickets are named as `receipts`, which could lead to confusion while reading the documentation. Also `check_receipts()` takes in the push-tickets as a parameter, but is named receipts, which could lead to confusion. `check_receipts()` seems to suggest that the function is checking the receipts itself, when its actually querying Expo _for_ the push-receipts. 

Is this a necessary change ? If you think it is, i'll make a pull request.
Thanks :)

**Comment by julianpacker** [comment]
If you're suggesting only name changes to be more conformant with the docs, I'm all for it. Create the PR and I'll push it through!

**Comment by SibiAkkash** [comment]
I created a PR #40
