### ISSUE TITLE
Adding tests?

### ISSUE THREAD

**Issue by jimcasteleiro** [expo-community/expo-server-sdk-python#39]
Hi - I noticed that this project doesn't contain any tests. I'm using this library in a project I'm working on, and would be happy to spend some time writing some tests. However, I didn't see anything about tests in the open/closed issues or pull requests, so I wasn't sure if there were any plans to add testing in the future/if any structure around that had been already discussed elsewhere. I wanted to hold off on investing any time on this until getting some feedback about what kinds of plans/work is already underway.

**Comment by julianpacker** [comment]
Hi, thanks for your interest.

No tests are currently being worked on. I think it's a great idea and I would love to see tests added in.

What were you thinking of having tests for?
