### ISSUE TITLE
ValueError: Invalid push token

### ISSUE THREAD

**Issue by tjhall13** [expo-community/expo-server-sdk-python#4]
A ValueError is thrown for push tokens not of type str. https://github.com/expo/exponent-server-sdk-python/blob/master/exponent_server_sdk/__init__.py#L207 in the code checks if the type of the token is `str`. This fails for objects of type unicode or other string like objects. Can this be a check that includes other string types or can it convert it to a str type before checking the prefix? If not, can this be better documented so we know it must be converted beforehand?

**Comment by odero** [comment]
Related PR https://github.com/expo/exponent-server-sdk-python/pull/5

**Comment by ide** [comment]
Merged #5 to support unicode objects. Published to PyPI as version 0.1.2.
