### ISSUE TITLE
error: invalid token. I want to send a push notification to multiple users

### ISSUE THREAD

**Issue by kevmai96** [expo-community/expo-server-sdk-python#48]
response = PushClient().publish(
        PushMessage(
            to=["ExponentPushToken[xxxxxxxxxxxxxxxxxx]","ExponentPushToken[xxxxxxxxxxxxxxxxxx]"],
            title=title,
            body=message,
            data=data
        )
    )

**Comment by julianpacker** [comment]
There's a publish_multiple function you can use.

Create multiple PushMessage objects and then pass that in
