### ISSUE TITLE
pip installing your sdk raises a module not found error

### ISSUE THREAD

**Issue by seandmatthews** [expo-community/expo-server-sdk-python#9]
Pip uses your setup.py file to find and install dependencies, however in your setup.py file on line 20 you import your exponent_server_sdk package which in turn imports six in it's __init__.py file. Pip hasn't gotten around to installing six yet, so this breaks.

I'm sure your oversight is only mildly irritating for most use cases, because you just manually install your dependencies first. If one's app sits in a docker container however, then it becomes moderately irritating to make sure that your dependencies installed before everything else because those are spun up from scratch with no manual intervention.

**Comment by anp** [comment]
Sorry about that! Submitted a PR internally for review.

**Comment by anp** [comment]
This is deployed to PyPI now, thanks for the heads up!
